name: HelpfulAdditions
version: ${project.version}
main: me.ej.HelpfulAdditions.EJessentials
api-version: 1.17
authors: [ EJ ]
description: Important things to have on your server!

commands:
  playeruuid:
    description: Gets the players UUID
    usage: /playeruuid
  helpfuladditions:
    description: Gives the info about plugin
    usage: /helpfuladditions
    permission: helpfuladditions.plugininfo
  currentlevel:
    description: Gives the player's level.
    usage: /currentlevel
  viewdistance:
    description: Gives the client view distance.
    usage: /viewdistance
  arrows:
    description: Gives the amount of arrows that are in the players body.
    usage: /arrows
permissions:
  helpfuladditions.plugininfo:
    description: Perm node for the /helpfuladditions command.
    default: not op
