name: HelpfulAdditions
version: ${project.version}
main: me.ej.HelpfulAdditions.EJessentials
api-version: 1.17
authors: [ EJ ]
description: Important things to have on your server!

commands:
  playeruuid:
    description: Gets the players UUID
    usage: /playeruuid
  online:
    description: shows online players
    usage: /online
  plugininfo:
    description: Gives the info about plugin
    usage: /plugininfo
    permission: helpfuladditions.plugininfo
permissions:
  helpfuladditions.plugininfo:
    description: Perm node for the /helpfuladditions command.
    default: not op
